In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime, timedelta

In [6]:
FILEPATH = "c:/Users/steve/Downloads/"

In [9]:
filename = FILEPATH + "UnderlyingOptionsEODCalcs_2023-12-07.csv"
options_df = pd.read_csv(filename)

In [10]:
options_df

,underlying_symbol,quote_date,root,expiration,strike,option_type,open,high,low,close,...,rho_1545,bid_size_eod,bid_eod,ask_size_eod,ask_eod,underlying_bid_eod,underlying_ask_eod,vwap,open_interest,delivery_code
0,SPY,2023-12-07,SPY,2023-12-07,387.0,C,71.05,71.25,71.00,71.00,...,0.0005,100,70.44,107,72.45,458.06,458.08,71.0875,10,NaN
1,SPY,2023-12-07,SPY,2023-12-07,387.0,P,0.01,0.01,0.01,0.01,...,0.0000,0,0.00,301,0.16,458.06,458.08,0.0100,337,NaN
2,SPY,2023-12-07,SPY,2023-12-07,388.0,C,0.00,0.00,0.00,0.00,...,0.0005,100,69.44,107,71.45,458.06,458.08,0.0000,0,NaN
3,SPY,2023-12-07,SPY,2023-12-07,388.0,P,0.00,0.00,0.00,0.00,...,0.0000,0,0.00,301,0.16,458.06,458.08,0.0000,26,NaN
4,SPY,2023-12-07,SPY,2023-12-07,389.0,C,0.00,0.00,0.00,0.00,...,0.0005,100,68.44,107,70.49,458.06,458.08,0.0000,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7977,SPY,2023-12-07,SPY,2026-01-16,670.0,P,0.00,0.00,0.00,0.00,...,-0.7233,201,210.50,200,215.36,458.06,458.08,0.0000,0,NaN
7978,SPY,2023-12-07,SPY,2026-01-16,675.0,C,0.00,0.00,0.00,0.00,...,0.5301,600,0.01,600,4.10,458.06,458.08,0.0000,0,NaN
7979,SPY,2023-12-07,SPY,2026-01-16,675.0,P,0.00,0.00,0.00,0.00,...,-0.5110,201,215.50,200,220.35,458.06,458.08,0.0000,0,NaN
7980,SPY,2023-12-07,SPY,2026-01-16,680.0,C,0.00,0.00,0.00,0.00,...,0.5497,0,0.00,600,3.92,458.06,458.08,0.0000,0,NaN
7981,SPY,2023-12-07,SPY,2026-01-16,680.0,P,0.00,0.00,0.00,0.00,...,-0.5154,201,220.50,200,225.34,458.06,458.08,0.0000,1,NaN